version: "3.7"
services:

  traefik:
    image: "traefik:2.2.8"
    command:
      # Try to enable this if something isn't working. 
      # Chances are, Traefik will tell you why.
      # Be careful in production as it exposes the traffic you might not want to expose.
      #--log.level=DEBUG

      --entrypoints.http.address=:80
      --entrypoints.https.address=:443

      --providers.docker=true

      --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
      --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    labels:
      # Redirect all HTTP traffic to HTTPS
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.to-https.entrypoints=http
      - traefik.http.routers.to-https.middlewares=to-https
      - traefik.http.middlewares.to-https.redirectscheme.scheme=https
    ports:
      - 80:80
      - 443:443
    volumes:
      - .data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
     depends_on:
       - db
     image: zdmc23/disciple.tools:0.31.1-mobile0.7-maarifa0.5.4
     volumes:
       - wp_data:/var/www/html
     restart: always
     environment:
       PORT: 80
       WORDPRESS_DB_HOST: db #:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: wordpress
     labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.wordpress.entrypoints=https
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=letsencrypt

volumes:
    db_data:
    wp_data:
